mass_arm: [10,0,0,0,0,0,
           0,10,0,0,0,0,
           0,0,68.37,0,0,0,
           0,0,0,1,0,0,
           0,0,0,0,1,0,
           0,0,0,0,0,1]
damping_arm: [78,0,0,0,0,0,
              0,34.2,0,0,0,0,
              0,0,171.7,0,0,0,
              0,0,0,1,0,0,
              0,0,0,0,1,0,
              0,0,0,0,0,1]
stiffness_coupling: [0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0]

base_link: "base_link"
end_link: "wrist_3_link"
# [position (x, y, z)  orientation (x, y, z, w)]

desired_pose:  [0.0,-0.8,0.40,       0.001, 0.99, 0.00, 0.001]

workspace_limits: [-0.80, 0.80, -0.5, 0.80, 0.30, 0.75]

arm_max_vel: 20
arm_max_acc: 50