kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1807731630767568
    roll: -0
    pitch: 0
    yaw: -3.567196658373073e-07
  upper_arm:
    x: -7.526718129907204e-06
    y: 0
    z: 0
    roll: 1.5702767898946
    pitch: 0
    yaw: 2.379880929952237e-06
  forearm:
    x: -0.6122023377421633
    y: 0
    z: 0
    roll: 0.001383046667496899
    pitch: 1.58411982918261e-05
    yaw: -5.407616254500743e-06
  wrist_1:
    x: -0.5714253025103897
    y: 0.001336896040280145
    z: 0.1738144889305027
    roll: 3.133901294335764
    pitch: -3.141045347281948
    yaw: -3.141587969438027
  wrist_2:
    x: 3.241530847319858e-05
    y: -0.1198328946891423
    z: 0.0001364870987870783
    roll: 1.569657348719462
    pitch: 0
    yaw: -1.054380885878291e-06
  wrist_3:
    x: -5.804270036782689e-06
    y: 0.1155809461295602
    z: 9.936569776019655e-05
    roll: 1.571656033144493
    pitch: 3.141592653589793
    yaw: 3.141592635020129
  hash: calib_5267357916444435967